# Generated by Django 4.2.6 on 2023-11-11 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('Addres_location', models.TextField()),
                ('id_manger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Curier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Addres_start_location', models.TextField()),
                ('grade', models.TextField()),
                ('Time_in_work', models.PositiveSmallIntegerField()),
                ('id_curier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
                ('id_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.manager')),
            ],
        ),
    ]
