# Generated by Django 4.2.6 on 2023-11-11 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_manager_curier'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addres_location', models.TextField(unique=True)),
                ('data_start_work', models.TextField()),
                ('cards_and_materials', models.BooleanField()),
                ('last_card_data', models.PositiveIntegerField()),
                ('count_happy_request', models.PositiveBigIntegerField()),
                ('count_give_card', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_task', models.TextField()),
                ('level_task', models.PositiveIntegerField()),
                ('time', models.FloatField()),
                ('addres_location', models.TextField(unique=True)),
                ('id_curier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.curier')),
                ('id_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.workpoint')),
            ],
        ),
    ]
